# 1. Import Libraries

In [88]:
!pip install transformers pandas torch
!pip install 'accelerate>=1.1.0'
!pip install scikit-learn
!pip install datasets

Requirement already satisfied: transformers in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (5.12.0)
Requirement already satisfied: pandas in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: torch in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (2.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (1.19.0)
Requirement already satisfied: numpy>=1.17 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (4.68.2)
Requirement already satisfied: click>=8.4.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.3)
Requirement already satisfied: fsspec>=2023.5.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: setuptools<82 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.2)
Requirement already satisfied: nvidia-cublas<=13.1.1.3,>=13.1.0.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (13.1.1.3)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.7.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (3.7.0)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-bindings<14,>=13.0.3->torch) (1.5.5)
Requirement already satisfied: six>=1.5 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from jinja2->torch) (3.0.3)

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: accelerate>=1.1.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (1.14.0)
Requirement already satisfied: numpy>=1.17 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (26.2)
Requirement already satisfied: psutil in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (7.2.2)
Requirement already satisfied: pyyaml in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (2.12.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (1.19.0)
Requirement already satisfied: safetensors>=0.4.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (0.8.0)
Requirement already satisfied: click>=8.4.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (3.29.3)
Requirement already satisfied: fsspec>=2023.5.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.68.2)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.15.0)
Requirement already satisfied: anyio in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.13.0)
Requirement already satisfied: certifi in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.0.9)
Requirement already satisfied: idna in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (3.18)
Requirement already satisfied: h11>=0.16 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.1.2)
Requirement already satisfied: setuptools<82 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.2)
Requirement already satisfied: nvidia-cublas<=13.1.1.3,>=13.1.0.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (13.1.1.3)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.4.5)

In [89]:
import pandas as pd
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer
import accelerate
from sklearn.preprocessing import LabelEncoder
from datasets import Dataset
import numpy as np
from sklearn.metrics import classification_report

# 2. Import Dataset and Train-test Split

In [90]:
df = pd.read_csv("../dataset/dataset_absa.csv")

labels = ["Negatif", "Positif"]

def encode_sentiment(dataframe):
    dataframe["labels"] = dataframe["sentiment"].apply(labels.index)
    return dataframe

def decode_sentiment(dataframe):
    dataframe["sentiment_decoded"] = dataframe["labels"].apply(lambda x: labels[x])
    return dataframe

df = encode_sentiment(df)


total_reviews = df["review_id"].max()

train_percentage = 0.8

max_id_train = total_reviews * train_percentage

train_df = df[df["review_id"] <= max_id_train]
test_df = df[df["review_id"] > max_id_train]

train_df

,review_id,review,aspect,sentiment,labels
0,1,Mata uang Asia 'rontok' berjamaah pada perdaga...,Mata uang Asia,Negatif,0
1,1,Mata uang Asia 'rontok' berjamaah pada perdaga...,Won Korea Selatan,Negatif,0
2,1,Mata uang Asia 'rontok' berjamaah pada perdaga...,Baht Thailand,Negatif,0
3,1,Mata uang Asia 'rontok' berjamaah pada perdaga...,Ringgit Malaysia,Negatif,0
4,1,Mata uang Asia 'rontok' berjamaah pada perdaga...,Dolar Singapura,Negatif,0
...,...,...,...,...,...
379,8,Kebijakan tarif impor baru yang ditetapkan Pre...,kesempatan emas,Positif,1
380,8,Kebijakan tarif impor baru yang ditetapkan Pre...,berbagai saham dengan fundamental yang baik,Positif,1
381,8,Kebijakan tarif impor baru yang ditetapkan Pre...,tekanan di pasar saham,Negatif,0
382,8,Kebijakan tarif impor baru yang ditetapkan Pre...,valuasi saham menjadi sangat murah,Positif,1
383,8,Kebijakan tarif impor baru yang ditetapkan Pre...,peluang untuk ekspansi,Positif,1

# 3. Import IndoBERT

In [91]:
model_name = "indobenchmark/indobert-base-p2"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 28850.25it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.weight | MISSING |
classifier.bias   | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

# 4. Fine Tune Model

In [92]:
train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

def tokenize(examples):
    return tokenizer(
        examples["review"],
        examples["aspect"],
        truncation=True,
        padding="max_length",
        max_length=128,
    )

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

train_dataset

Map: 100%|██████████| 384/384 [00:00<00:00, 1000.91 examples/s]
Map: 100%|██████████| 46/46 [00:00<00:00, 1864.89 examples/s]

Dataset({
    features: ['review_id', 'review', 'aspect', 'sentiment', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 384
})

In [93]:
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=5,
    per_device_train_batch_size=16,
    learning_rate=2e-5,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)

trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.52s/it]

TrainOutput(global_step=120, training_loss=0.4335107167561849, metrics={'train_runtime': 45.9483, 'train_samples_per_second': 41.786, 'train_steps_per_second': 2.612, 'total_flos': 126293306572800.0, 'train_loss': 0.4335107167561849, 'epoch': 5.0})

# 5. Predict

In [ ]:
predictions = trainer.predict(test_dataset)
pred_ids = np.argmax(predictions.predictions, axis=1)

predictions_df = pd.DataFrame({
    "prediction": [labels[i] for i in pred_ids]
})

predictions_df["actuals"] = test_df.reset_index(drop=True)["sentiment"]
predictions_df["review_id"] = test_df.reset_index(drop=True)["review_id"]
predictions_df["sentiment"] = test_df.reset_index(drop=True)["sentiment"]
predictions_df

   prediction  actuals
0     Negatif  Positif
1     Positif  Positif
2     Negatif  Positif
3     Positif  Positif
4     Positif  Positif
5     Negatif  Negatif
6     Positif  Positif
7     Positif  Positif
8     Positif  Positif
9     Positif  Positif
10    Positif  Positif
11    Negatif  Positif
12    Positif  Positif
13    Negatif  Positif
14    Negatif  Positif
15    Positif  Positif
16    Negatif  Negatif
17    Negatif  Negatif
18    Negatif  Negatif
19    Negatif  Negatif
20    Negatif  Positif
21    Negatif  Positif
22    Positif  Positif
23    Negatif  Negatif
24    Negatif  Negatif
25    Negatif  Negatif
26    Positif  Negatif
27    Positif  Positif
28    Positif  Positif
29    Negatif  Negatif
30    Negatif  Negatif
31    Negatif  Negatif
32    Negatif  Negatif
33    Positif  Positif
34    Negatif  Negatif
35    Positif  Positif
36    Positif  Positif
37    Positif  Positif
38    Positif  Positif
39    Negatif  Negatif
40    Positif  Positif
41    Positif  Positif
42    Negatif  Positif
43    Negatif  Positif
44    Negatif  Positif
45    Positif  Negatif

# 6. Evaluate

In [95]:
print(
    classification_report(
        test_df["labels"],
        pred_ids,
        target_names=["Negatif", "Positif"]
    )
)

              precision    recall  f1-score   support

     Negatif       0.58      0.88      0.70        16
     Positif       0.91      0.67      0.77        30

    accuracy                           0.74        46
   macro avg       0.75      0.77      0.73        46
weighted avg       0.80      0.74      0.75        46

#