# 1. Import Libraries

In [9]:
!pip install transformers pandas torch
!pip install 'accelerate>=1.1.0'
!pip install scikit-learn
!pip install datasets

Requirement already satisfied: transformers in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (5.12.0)
Requirement already satisfied: pandas in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: torch in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (2.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (1.19.0)
Requirement already satisfied: numpy>=1.17 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from transformers) (4.68.2)
Requirement already satisfied: click>=8.4.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.3)
Requirement already satisfied: fsspec>=2023.5.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: setuptools<82 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.2)
Requirement already satisfied: nvidia-cublas<=13.1.1.3,>=13.1.0.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (13.1.1.3)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.7.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch) (3.7.0)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-bindings<14,>=13.0.3->torch) (1.5.5)
Requirement already satisfied: six>=1.5 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from jinja2->torch) (3.0.3)

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: accelerate>=1.1.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (1.14.0)
Requirement already satisfied: numpy>=1.17 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (26.2)
Requirement already satisfied: psutil in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (7.2.2)
Requirement already satisfied: pyyaml in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (2.12.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (1.19.0)
Requirement already satisfied: safetensors>=0.4.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from accelerate>=1.1.0) (0.8.0)
Requirement already satisfied: click>=8.4.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (3.29.3)
Requirement already satisfied: fsspec>=2023.5.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.68.2)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.15.0)
Requirement already satisfied: anyio in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.13.0)
Requirement already satisfied: certifi in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.0.9)
Requirement already satisfied: idna in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (3.18)
Requirement already satisfied: h11>=0.16 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.1.2)
Requirement already satisfied: setuptools<82 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.2)
Requirement already satisfied: nvidia-cublas<=13.1.1.3,>=13.1.0.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (13.1.1.3)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/lenovo/Documents/School/Sem6/PBA/pba-task-final-individual/.env/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.4.5)

In [10]:
import pandas as pd
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer
import accelerate
from sklearn.preprocessing import LabelEncoder
from datasets import Dataset
import numpy as np
from sklearn.metrics import classification_report

# 2. Import Dataset and Train-test Split

In [11]:
df = pd.read_csv("../dataset/dataset.csv")

labels = ["Negatif", "Positif"]

def encode_sentiment(dataframe):
    dataframe["labels"] = dataframe["sentiment"].apply(labels.index)
    return dataframe

def decode_sentiment(dataframe):
    dataframe["sentiment_decoded"] = dataframe["labels"].apply(lambda x: labels[x])
    return dataframe

df = encode_sentiment(df)


total_reviews = df["review_id"].max()

train_percentage = 0.8

max_id_train = total_reviews * train_percentage

train_df = df[df["review_id"] <= max_id_train]
test_df = df[df["review_id"] > max_id_train]

train_df

,url,judul,review,sentiment,review_id,labels
0,https://www.cnbcindonesia.com/research/2025012...,Trump Sebar Exceutive Order: Emang Semengerika...,"Jakarta, CNBC Indonesia -Amerika Serikat (AS) ...",Positif,1,1
1,https://www.cnbcindonesia.com/research/2025012...,"Alasan Rupiah 'Berpesta' di Pelantikan Trump, ...","Jakarta, CNBC Indonesia -Nilai tukar rupiah te...",Positif,2,1
2,https://www.cnbcindonesia.com/research/2025012...,"Trump Beri Kabar Baik, Saatnya Menunggu Dolar ...","Jakarta, CNBC Indonesia-Pasar keuangan Indones...",Positif,3,1
3,https://www.cnbcindonesia.com/research/2025030...,"IHSG Merah Lagi, Begini Penjelasan dari Analis...","Jakarta, CNBC Indonesia -Indeks Harga Saham Ga...",Negatif,4,0
4,https://indodax.com/academy/bitcoin-200k-predi...,Bernstein: Bitcoin Bisa Naik 2x Lipat! Target ...,HargaBitcoin(BTC)pernah melewati angka terting...,Positif,5,1
...,...,...,...,...,...,...
795,https://www.cnbcindonesia.com/tech/20250506105...,"Tarif Trump Sia-sia, Ini Alasan China Tak Bisa...","Jakarta, CNBC Indonesia -Usaha Trump untuk mem...",Negatif,796,0
796,https://megapolitan.antaranews.com/berita/3932...,Tarif Trump dan ujian diplomasi Indonesia - AN...,"Senin, 5 Mei 2025 13:31 WIB\nPemerintah Indone...",Positif,797,1
797,https://www.bloombergtechnoz.com/detail-news/7...,Donald Trump Isyaratkan akan Turunkan Tarif Im...,"Kasia Klimasinska - Bloomberg News\nBloomberg,...",Positif,798,1
798,https://www.antaranews.com/berita/4817485/bea-...,Bea Cukai: Penundaan tarif Trump pacu produksi...,Batam (ANTARA) - Kepala Kantor Pelayanan Utama...,Positif,799,1
799,https://www.cnbcindonesia.com/lifestyle/202505...,"Imbas Tarif Trump, Industri Fesyen RI Putar Ot...","Jakarta, CNBC Indonesia- Pelaku usaha di indus...",Negatif,800,0

# 3. Import IndoBERT

In [12]:
model_name = "indobenchmark/indobert-base-p2"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 36168.76it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

# 4. Fine Tune Model

In [13]:
train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

def tokenize(examples):
    return tokenizer(
        examples["review"],
        truncation=True,
        padding="max_length",
        max_length=128,
    )

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

train_dataset

Map: 100%|██████████| 800/800 [00:00<00:00, 1725.51 examples/s]
Map: 100%|██████████| 201/201 [00:00<00:00, 1891.19 examples/s]

Dataset({
    features: ['url', 'judul', 'review', 'sentiment', 'review_id', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 800
})

In [14]:
training_args = TrainingArguments(
    output_dir="./results2",
    num_train_epochs=5,
    per_device_train_batch_size=16,
    learning_rate=2e-5,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)

trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.34it/s]

TrainOutput(global_step=250, training_loss=0.3735402221679687, metrics={'train_runtime': 111.566, 'train_samples_per_second': 35.853, 'train_steps_per_second': 2.241, 'total_flos': 263111055360000.0, 'train_loss': 0.3735402221679687, 'epoch': 5.0})

# 5. Predict

In [15]:
predictions = trainer.predict(test_dataset)
pred_ids = np.argmax(predictions.predictions, axis=1)

predictions_df = pd.DataFrame({
    "prediction": [labels[i] for i in pred_ids]
})

predictions_df["actuals"] = test_df.reset_index(drop=True)["sentiment"]
predictions_df["review_id"] = test_df.reset_index(drop=True)["review_id"]
predictions_df["sentiment"] = test_df.reset_index(drop=True)["sentiment"]
predictions_df

    prediction  actuals  review_id sentiment
0      Negatif  Positif        801   Positif
1      Positif  Positif        802   Positif
2      Negatif  Positif        803   Positif
3      Positif  Positif        804   Positif
4      Positif  Positif        805   Positif
..         ...      ...        ...       ...
196    Positif  Positif        997   Positif
197    Negatif  Positif        998   Positif
198    Negatif  Negatif        999   Negatif
199    Positif  Negatif       1000   Negatif
200    Negatif  Negatif       1001   Negatif

[201 rows x 4 columns]

# 6. Evaluate

In [16]:
print(
    classification_report(
        test_df["labels"],
        pred_ids,
        target_names=["Negatif", "Positif"]
    )
)

              precision    recall  f1-score   support

     Negatif       0.50      0.82      0.62        72
     Positif       0.84      0.53      0.65       129

    accuracy                           0.64       201
   macro avg       0.67      0.68      0.64       201
weighted avg       0.72      0.64      0.64       201

#